on:
  push:
    branches:
    - master
name: Run the tool
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: CPP Evaluation
        uses: jamespwilliams/cpp-evaluation-action
