on: push
name: CPP Evaluator
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: CPP Evaluation
        uses: luke142367/cpp-evaluation-action@0.0.1
