on: push
name: CPP Evaluator
jobs:
  cpp_spark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: C++ Evaluation
        uses: luke142367/cpp-evaluation-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
